#cloud-config
write_files:
  - path: /tmp/userdata.sh
    permissions: '0755'
    content: |
      ${file("scripts/userdata.sh")}

users:
  - default
  - name: ${USERNAME}
    gecos: ${USERNAME}
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: wheel
    lock_passwd: false
    ssh-authorized-keys:
      - ${PUBLIC_KEY_CONTENT}

runcmd:
  - /tmp/userdata.sh
